version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo2020
    ports:
      - "27017:27017"
    volumes:
      - ./backend/mongoDb:/data/db
  db:
    image: postgres
    volumes:
      - ./backend/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
  node:
    build: .
    image: gobarber:2.0
    command: yarn dev
    volumes:
      -  ./backend:/app/
    ports:
      - "3333:3333"
    depends_on:
      - db
      - mongo
      - redis
